### ISSUE TITLE
Disable both RESET and DOWNLOAD buttons when there is nothing to download

### ISSUE THREAD

**Issue by demonlexe** [demonlexe/netflix-to-anki#26]

**Comment by Vishak11** [comment]
@demonlexe Could you assign this to me

**Comment by demonlexe** [comment]
> @demonlexe Could you assign this to me

Sure, feel free to take a stab at it! If you need help with anything let me know. My discord is demonlexe aswell.

**Comment by demonlexe** [comment]
@Vishak11 Hey, since it's not been started yet, I've reassigned this to @LavinaU since she is ready to complete it. If you want to work on something else, let me know!
